In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("D:/Data Science/Symbiosis/KNN/Ad_purchace.csv")

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [13]:
df.isnull().sum()

User ID              0
Gender             400
Age                  0
EstimatedSalary      0
Purchased            0
dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Gender"]=le.fit_transform(df["Gender"])

In [17]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       0   19            19000          0
1  15810944       0   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       0   19            76000          0

In [45]:
x=df.drop(columns=["User ID","Purchased"])
y=df["Purchased"]

In [19]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
model=KNeighborsClassifier(n_neighbors=5)
model.fit(xtrain,ytrain)

KNeighborsClassifier()

In [22]:
ypred=model.predict(xtest)
ypred

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(ytest,ypred)

In [24]:
acc

0.8125

In [25]:
cm=confusion_matrix(ytest,ypred)
cm

array([[38,  5],
       [10, 27]], dtype=int64)

In [26]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.79      0.88      0.84        43
           1       0.84      0.73      0.78        37

    accuracy                           0.81        80
   macro avg       0.82      0.81      0.81        80
weighted avg       0.82      0.81      0.81        80



In [27]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
scale_x=sc.fit_transform(x)


In [35]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [36]:
model_sc=KNeighborsClassifier(n_neighbors=5)
model_sc.fit(xtrain,ytrain)

KNeighborsClassifier()

In [37]:
ypred=model_sc.predict(xtest)
ypred

array([0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0], dtype=int64)

In [38]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(ytest,ypred)

In [39]:
acc

0.85

In [40]:
cm=confusion_matrix(ytest,ypred)
cm

array([[51,  3],
       [ 9, 17]], dtype=int64)

In [41]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.85      0.94      0.89        54
           1       0.85      0.65      0.74        26

    accuracy                           0.85        80
   macro avg       0.85      0.80      0.82        80
weighted avg       0.85      0.85      0.84        80



In [42]:
#n_neighbors


In [49]:
#estimator
model=KNeighborsClassifier()
#parameter
n_neighbors=range(1,31)
metric=["euclidean","manhattan","minkowski"]
weights=["uniform","distance"]
#parameter grid
grid={"n_neighbors":n_neighbors,"metric":metric,"weights":weights}

#cross validation
from sklearn.model_selection import RepeatedStratifiedKFold
kfold_cv=RepeatedStratifiedKFold(n_splits=5,n_repeats=3,random_state=0)

#grid Search cv

from sklearn.model_selection import GridSearchCV
grid_cv=GridSearchCV(estimator=model,param_grid=grid,cv=kfold_cv,scoring="accuracy",n_jobs=1)
res=grid_cv.fit(xtrain,ytrain)

In [50]:
res.best_params_

{'metric': 'euclidean', 'n_neighbors': 1, 'weights': 'uniform'}

In [51]:
res.best_score_

0.8041666666666667