In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder() 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

In [2]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

d={"data":["red","green","blue"]}
df=pd.DataFrame(d)
oh=OneHotEncoder()
print(oh.fit_transform(df[["data"]]))
print(oh.fit_transform(df[["data"]]).toarray())

  (0, 2)	1.0
  (1, 1)	1.0
  (2, 0)	1.0
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [3]:
x={"data":["S","M","L","XL","XXL"]}
df=pd.DataFrame(x)
oh=OneHotEncoder()
print(oh.fit_transform(df[["data"]]))
print(oh.fit_transform(df[["data"]]).toarray())

  (0, 2)	1.0
  (1, 1)	1.0
  (2, 0)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
[[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
#various inflation factor
#VIF<5 (this is moderate)
#VIF>5 to avoid this drop one encoding column